spring:
  application:
    name: integration-test
  datasource:
    url: jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=false;MODE=MySQL
    username: sa
    password:
  jpa:
    hibernate:
      ddl-auto: validate
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
server:
  port: 0
fakturownia:
  url: http://localhost:3000
  token: test-token
http:
  cors:
    swagger-ui:
      enabled: false