spring:
  application:
    name: integration-test
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
    open-in-view: false
  liquibase:
    enabled: true
    change-log: classpath:/db/changelog/db.changelog-master.yaml
server:
  port: 0
fakturownia:
  url: http://localhost:3000
  token: test-token
webhooks:
  clients:
    fakturownia:
      enabled: true
      shared-secret: secret
      requests-per-minute-limit: 60
